# Generated by Django 2.2.4 on 2019-09-03 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='publishd_date',
            new_name='published_date',
        ),
    ]
